# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Elias Trommer'
tagline:          'Bits and Electrons'
description:      'doing digital stuff'
url:              https://etrommer.github.io

author:
    name:         'Elias Trommer'

social-network-links:
    github:       https://github.com/jadeaffenjaeger
    linkedin:     https://www.linkedin.com/in/elias-trommer-58a085138

# 10 entries per page
paginate: 10

plugins:
    - jekyll-feed
    - jekyll-gist
    - jekyll-paginate
    - jekyll-sitemap

# Sidebar link settings
sidebar_home_link:  true
